#!/bin/sh

PRODUCT=scylla
VERSION=5.1.0-dev

if test -f version
then
	SCYLLA_VERSION=$(cat version | awk -F'-' '{print $1}')
	SCYLLA_RELEASE=$(cat version | awk -F'-' '{print $2}')
else
	DATE=$(date +%Y%m%d)
	GIT_COMMIT=$(git log --pretty=format:'%h' -n 1)
	SCYLLA_VERSION=$(echo $VERSION | awk -F'-' '{print $1}')
	RELEASE_CANDIDATE=$(echo $VERSION | awk -F'-' '{print $2}')
	if [ -z $RELEASE_CANDIDATE ]; then
	  SCYLLA_RELEASE=$DATE.$GIT_COMMIT
	else
	  SCYLLA_RELEASE=$RELEASE_CANDIDATE.$DATE.$GIT_COMMIT
	fi
fi

echo "$SCYLLA_VERSION-$SCYLLA_RELEASE"
mkdir -p build
echo "$SCYLLA_VERSION" > build/SCYLLA-VERSION-FILE
echo "$SCYLLA_RELEASE" > build/SCYLLA-RELEASE-FILE
echo "$PRODUCT" > build/SCYLLA-PRODUCT-FILE
