#!/usr/bin/env python3
#
# Copyright 2020 ScyllaDB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import sys
from pathlib import Path
from subprocess import run, PIPE


def get_nvme_devices():
    result = run(["ls /dev/nvme0n*"], stdout=PIPE, text=True, shell=True)
    devices = result.stdout.strip().split()
    assert devices, "No NVMe devices found!"
    return devices


def create_raid(devices):
    scylla_path = Path("/var/lib/scylla")
    if scylla_path.is_mount():
        print(f"{scylla_path} is already mounted. Will not run 'scylla_raid_setup'!")
        sys.exit(0)
    run(["/opt/scylladb/scripts/scylla_raid_setup", "--raiddev", "/dev/md0", "--disks", ",".join(devices),
        "--root", "/var/lib/scylla", "--volume-role", "all", "--update-fstab"], check=True)


if __name__ == "__main__":
    nvme_devices = get_nvme_devices()
    create_raid(devices=nvme_devices)


