#!/usr/bin/python3
#
# Copyright 2018 ScyllaDB
#

#
# This file is part of Scylla.
#
# Scylla is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Scylla is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Scylla.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import pathlib
sys.path.append('/opt/scylladb/scripts')
from scylla_util import *

if __name__ == '__main__':
    aws = aws_instance()
    run('/opt/scylladb/scylla-cloud-image/scylla_configure.py')
    run('/opt/scylladb/scylla-cloud-image/scylla_create_devices')
    run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami')
    if aws.is_supported_instance_class():
        run('/opt/scylladb/scripts/scylla_io_setup --ami')
    if os.path.ismount('/var/lib/scylla'):
        run('/opt/scylladb/scripts/scylla_coredump_setup --dump-to-raiddir')
    else:
        run('/opt/scylladb/scripts/scylla_coredump_setup')
    pathlib.Path('/etc/scylla/cloud_image_configured').touch()
                                                                                                                        