#!/usr/bin/python3
#
# Copyright 2020 ScyllaDB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import pathlib
sys.path.append('/opt/scylladb/scripts')
from scylla_util import *

if __name__ == '__main__':
    aws = aws_instance()
    run('/opt/scylladb/scylla-machine-image/scylla_configure.py')
    run('/opt/scylladb/scylla-machine-image/scylla_create_devices')
    run('/opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic --ami')
    if aws.is_supported_instance_class():
        run('/opt/scylladb/scripts/scylla_io_setup --ami')
    if os.path.ismount('/var/lib/scylla'):
        run('/opt/scylladb/scripts/scylla_coredump_setup --dump-to-raiddir')
    else:
        run('/opt/scylladb/scripts/scylla_coredump_setup')
    run('/opt/scylladb/scripts/scylla_swap_setup --swap-directory /')
    pathlib.Path('/etc/scylla/machine_image_configured').touch()
                                                                                                                        