#!/usr/bin/env python3
#
# Copyright 2020 ScyllaDB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import sys
from pathlib import Path
from subprocess import run


sys.path.append('/opt/scylladb/scripts')
from scylla_util import is_ec2, is_gce, is_azure, get_cloud_instance


def create_raid(devices):
    scylla_path = Path("/var/lib/scylla")
    print(f"Devices: {devices}")
    if scylla_path.is_mount():
        print(f"{scylla_path} is already mounted. Will not run 'scylla_raid_setup'!")
        sys.exit(0)
    run(["/opt/scylladb/scripts/scylla_raid_setup", "--raiddev", "/dev/md0", "--disks", ",".join(devices),
         "--root", "/var/lib/scylla", "--volume-role", "all", "--update-fstab"], check=True)


def check_persistent_disks_are_empty(disks):
    for disk in disks:
        part = run(f'lsblk -dpnr -o PTTYPE /dev/{disk}', shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip()
        fs = run(f'lsblk -dpnr -o FSTYPE /dev/{disk}', shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip()
        if part != '' or fs != '':
            raise Exception(f"/dev/{disk} is not empty, abort formatting")


def get_disk_devices(instance, device_type):
    if is_ec2():
        devices = []
        if device_type == "attached":
            check_persistent_disks_are_empty(instance.ebs_disks())
            devices = [str(Path('/dev', name)) for name in instance.ebs_disks() if Path('/dev', name).exists()]
        if not devices or device_type == "instance_store":
            devices = [str(Path('/dev', name)) for name in instance.ephemeral_disks()]
        if not devices:
            raise Exception(f"No block devices were found for '{device_type}' device type")
        return devices
    elif is_gce():
        return get_default_devices(instance)
    elif is_azure():
        return get_default_devices(instance)
    else:
        raise Exception("Running in unknown cloud environment")


def get_default_devices(instance):
    disk_names = []
    if is_ec2():
        disk_names = instance.ephemeral_disks()
        if not disk_names:
            disk_names = instance.ebs_disks()
            check_persistent_disks_are_empty(disk_names)
    elif is_gce():
        disk_names = instance.getEphemeralOsDisks()
        if not disk_names:
            disk_names = instance.getPersistentOsDisks()
            check_persistent_disks_are_empty(disk_names)
    elif is_azure():
        disk_names = instance.getEphemeralOsDisks()
        if not disk_names:
            disk_names = instance.getPersistentOsDisks()
            check_persistent_disks_are_empty(disk_names)
    else:
        raise Exception("Running in unknown cloud environment")
    return [str(Path('/dev', name)) for name in disk_names]


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Disk creation script for Scylla.')
    parser.add_argument('--data-device', dest='data_device', action='store',
                        choices=["auto", "attached", "instance_store"],
                        help='Define type of device to use for scylla data: attached|instance_store')
    args = parser.parse_args()

    instance = get_cloud_instance()

    if not args.data_device or args.data_device == "auto":
        disk_devices = get_default_devices(instance)
    else:
        disk_devices = get_disk_devices(instance, args.data_device)

    if len(disk_devices) == 0:
        print('No data disks found')
    else:
        create_raid(disk_devices)
