#!/usr/bin/env python3
#
# Copyright 2022 ScyllaDB
#
# SPDX-License-Identifier: Apache-2.0

import argparse
import os
import re
import sys

from lib.scylla_cloud import AwsInstance, colorprint, is_ec2, out


if __name__ == "__main__":
    if not is_ec2():
        sys.exit(0)
    parser = argparse.ArgumentParser(description="Verify EC2 configuration is optimized.")
    parser.add_argument("--nic", default="eth0", help="specify NIC")
    args = parser.parse_args()

    if not os.path.exists(f"/sys/class/net/{args.nic}"):
        print(f"NIC {args.nic} doesn't exist.")
        sys.exit(1)

    aws = AwsInstance()
    instance_class = aws.instance_class()
    en = aws.get_en_interface_type()
    match = re.search(r"^driver: (\S+)$", out(f"ethtool -i {args.nic}"), flags=re.MULTILINE)
    driver = match.group(1)

    if not en:
        colorprint("{red}{instance_class} doesn't support enhanced networking!{nocolor}", instance_class=instance_class)
        print("""To enable enhanced networking, please use the instance type which supports it.
More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking""")
        sys.exit(1)
    elif not aws.is_vpc_enabled(args.nic):
        colorprint("{red}VPC is not enabled!{nocolor}")
        print("To enable enhanced networking, please enable VPC.")
        sys.exit(1)
    elif driver != en:
        colorprint("{red}Enhanced networking is disabled!{nocolor}")
        print("""More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html""")
        sys.exit(1)

    colorprint("{green}This EC2 instance is optimized for Scylla.{nocolor}")
