#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2022 ScyllaDB
#
# SPDX-License-Identifier: Apache-2.0

import os
import sys
import re
import argparse
from lib.scylla_cloud import is_ec2, aws_instance, colorprint, out
from subprocess import run

if __name__ == '__main__':
    if not is_ec2():
        sys.exit(0)
    parser = argparse.ArgumentParser(description='Verify EC2 configuration is optimized.')
    parser.add_argument('--nic', default='eth0',
                        help='specify NIC')
    args = parser.parse_args()

    if not os.path.exists(f'/sys/class/net/{args.nic}'):
        print('NIC {} doesn\'t exist.'.format(args.nic))
        sys.exit(1)

    aws = aws_instance()
    match = re.search(r'^driver: (\S+)$', out(f'ethtool -i {args.nic}'), flags=re.MULTILINE)
    if not match:
        colorprint('{red}Unable to determine NIC driver!{nocolor}')
        sys.exit(1)
    
    driver = match.group(1)
    
    # Check if enhanced networking is enabled by verifying the driver
    if driver not in ['ena', 'ixgbevf']:
        colorprint('{red}Enhanced networking is not enabled on {nic}!{nocolor}', nic=args.nic)
        print(f'Current NIC driver: {driver}')
        print('''Enhanced networking requires ena or ixgbevf driver.
The NIC hardware may support enhanced networking, but the current driver does not.
To enable enhanced networking, please use an instance type that supports it and ensure
the correct drivers are loaded.
More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking''')
        sys.exit(1)
    
    if not aws.is_vpc_enabled(args.nic):
        colorprint('{red}VPC is not enabled!{nocolor}')
        print('To enable enhanced networking, please enable VPC.')
        sys.exit(1)

    colorprint('{green}This EC2 instance is optimized for Scylla.{nocolor}')
