#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright 2022 ScyllaDB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import re
import argparse
sys.path.append('/opt/scylladb/scripts')
from scylla_util import is_valid_nic, colorprint
from lib.scylla_cloud import is_ec2, aws_instance
from subprocess import run

if __name__ == '__main__':
    if not is_ec2():
        sys.exit(0)
    parser = argparse.ArgumentParser(description='Verify EC2 configuration is optimized.')
    parser.add_argument('--nic', default='eth0',
                        help='specify NIC')
    args = parser.parse_args()

    if not is_valid_nic(args.nic):
        print('NIC {} doesn\'t exist.'.format(args.nic))
        sys.exit(1)

    aws = aws_instance()
    instance_class = aws.instance_class()
    en = aws.get_en_interface_type()
    match = re.search(r'^driver: (\S+)$', run('ethtool -i {}'.format(args.nic), shell=True, check=True, capture_output=True, encoding='utf-8').stdout.strip(), flags=re.MULTILINE)
    driver = match.group(1)

    if not en:
        colorprint('{red}{instance_class} doesn\'t support enhanced networking!{nocolor}', instance_class=instance_class)
        print('''To enable enhanced networking, please use the instance type which supports it.
More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking''')
        sys.exit(1)
    elif not aws.is_vpc_enabled(args.nic):
        colorprint('{red}VPC is not enabled!{nocolor}')
        print('To enable enhanced networking, please enable VPC.')
        sys.exit(1)
    elif driver != en:
        colorprint('{red}Enhanced networking is disabled!{nocolor}')
        print('''More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html''')
        sys.exit(1)

    colorprint('{green}This EC2 instance is optimized for Scylla.{nocolor}')
