name: Call Jira Status In Review

on:
  pull_request:
    types: [ready_for_review, review_requested]

jobs:
  call-jira-status-in-review:
    uses: scylladb/github-automation/.github/workflows/main_update_jira_status_to_in_review.yml@main
    secrets:
      jira_auth: ${{ secrets.USER_AND_KEY_FOR_JIRA_AUTOMATION }}
    steps:
      - name: Check if JIRA_AUTH secret is available
        run: |
          if [ -z "${{ secrets.USER_AND_KEY_FOR_JIRA_AUTOMATION }}" ]; then
            echo "JIRA_AUTH secret NOT found."
          else
            echo "JIRA_AUTH secret found."
          fi
